#!/usr/bin/env bash

sudo apt update
pip3 install gunicorn
sudo ufw allow 5000
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
<evops-master/0x1A-application_server/gunicorn_setup" 5L, 79C 1,1  
